name: wedding_s_w
description: The app for the wedding
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: '>=0.0.0 <1.0.0'
  cloud_firestore: '>=4.0.0 <5.0.0'
  firebase_app_check: '>=0.0.0 <1.0.0'
  firebase_core: '>=2.0.0 <3.0.0'
  firebase_storage: '>=11.0.0 <12.0.0'
  firebase_crashlytics: '>=3.0.0 <4.0.0'
  get_it: '>=7.0.0 <8.0.0'
  photo_view: '>=0.0.0 <1.0.0'
  share_plus: '>=7.0.0 <8.0.0'
  url_launcher: '>=6.0.0 <7.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: '>=2.0.0 <3.0.0'

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay.ttf