name: shared
description: Shared library between the admin app and user app
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  behaviour: '>=2.0.0 <3.0.0'
  cached_network_image: '>=3.0.0 <4.0.0'
  cloud_firestore: '>=4.0.0 <5.0.0'
  firebase_app_check: '>=0.0.0 <1.0.0'
  firebase_auth: '>=4.0.0 <5.0.0'
  firebase_core: '>=2.0.0 <3.0.0'
  firebase_crashlytics: '>=3.0.0 <4.0.0'
  firebase_remote_config: '>=4.0.0 <5.0.0'
  firebase_storage: '>=11.0.0 <12.0.0'
  flutter:
    sdk: flutter
  flutter_fox_logging: '>=1.0.0 <2.0.0'
  get_it: '>=7.0.0 <8.0.0'
  infinite_scroll_pagination: '>=3.0.0 <4.0.0'
  photo_view: '>=0.0.0 <1.0.0'
  share_plus: '>=7.0.0 <8.0.0'
  spotify: '>=0.0.0 <1.0.0'

dev_dependencies:
  auto_route_generator: '>=7.0.0 <8.0.0'
  build_runner:
  flutter_test:
    sdk: flutter
  lint: '>=2.0.0 <3.0.0'

flutter:
  uses-material-design: true
