name: Release

on:
  push:
    tags:
      - 'v*'
      
jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Android 🤖
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: android
          
      - name: Download web 🌐
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: web
          path: web
          
      - name: Zip web
        uses: thedoctor0/zip-release@0.7.0
        with:
          type: 'zip'
          path: web
          filename: wedding_s_w-web.zip
          
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "wedding_s_w.apk,wedding_s_w.aab,wedding_s_w-web.zip"
          
  publish-to-github-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          name: githubPages
          path: _site
      
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
