name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  code_quality_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3      
      
      - name: Install flutter
        uses: subosito/flutter-action@v2
      - run: flutter doctor -v

      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Create Firebase options
        run: |
          echo "$FIREBASE_OPTIONS_DART" > lib/firebase_options.dart
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        working-directory: ./app

      - run: |
          cat app/lib/firebase_options.dart
        
      - name: Verify formatting
        working-directory: ./app
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        working-directory: ./app
        run: dart analyze --fatal-infos
        
